### ISSUE TITLE
How do I commit 2 new classes?

### ISSUE THREAD

**Issue by erik1961** [onware/TableauAPI#2]
New at github, how can I upload 2 new classes?
Regards
Erik

**Comment by fgallop** [comment]
Hi there,

If you create a pull request, I can merge it:

https://help.github.com/articles/about-pull-requests/

Regards,

-Fraser

**Comment by erik1961** [comment]
Hi again,
I have uploaded a repository called etl1961/TableauAPI

Can that be used in the Pull request ?

Regards
Erik
